<a href="https://colab.research.google.com/github/Arjun650/MachineLearning/blob/main/Lab_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import numpy.linalg as la

In [2]:

df = pd.read_excel('labSession.xlsx')
df = df.dropna(axis = 1)
df


Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [3]:
A = df.iloc[:, 1:-1].values
B =df.iloc[:, -1].values

A = np.array(A)
B = np.array(B)

print("Matrix A :")
print(A)
print("Matrix B :")
print(B)

# number of vectors
noOfVector = A.shape[0]
print('Number of vector is : ', noOfVector)


# Dimensionality
DimensionalityOfA = A.shape[1]
DimensionalityOfB = A.shape[1]
print("Dimensionality of A is" , DimensionalityOfA)
print("Dimensionality of B is" , DimensionalityOfB)



Matrix A :
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Matrix B :
[386 289 393 110 280 167 271 274 148 198]
Number of vector is :  10
Dimensionality of A is 3
Dimensionality of B is 3


In [4]:
rank = np.linalg.matrix_rank(A)
print("Rank of matrix A is", rank)

Rank of matrix A is 3


In [5]:
# Using Pseudo-Inverse find the cost of each product available for sale.
# (Suggestion: If you use Python, you can use numpy.linalg.pinv() function to get a
# pseudo-inverse.)

pseudoInverse = np.linalg.pinv(A)
priceEachProduct = pseudoInverse.dot(B)
priceEachProduct = np.array(priceEachProduct)
print(priceEachProduct)

[ 1. 55. 18.]


In [7]:
# . Use the Pseudo-inverse to calculate the model vector X for predicting the cost of the products
# available with the vendor.

X = np.dot(pseudoInverse, B)
print(X)

[ 1. 55. 18.]


In [10]:
# Mark all customers (in “Purchase Data” table) with payments above Rs. 200 as RICH and others
# as POOR. Develop a classifier model to categorize customers into RICH or POOR class based on
# purchase behavior.

df['Category'] = df['Payment (Rs)'] > 200
df['Category'] = df['Category'].replace({True:'Rich', False:'Poor'})

print(df)


  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Category
0      C_1           20             6                 2           386     Rich
1      C_2           16             3                 6           289     Rich
2      C_3           27             6                 2           393     Rich
3      C_4           19             1                 2           110     Poor
4      C_5           24             4                 2           280     Rich
5      C_6           22             1                 5           167     Poor
6      C_7           15             4                 2           271     Rich
7      C_8           18             4                 2           274     Rich
8      C_9           21             1                 4           148     Poor
9     C_10           16             2                 4           198     Poor
